image: alpine/edge
triggers:
  - action: email
    condition: failure
    to: Sebastian LaVine <mail@smlavine.com>
packages:
  - sdl2-dev
  - gcc
  - clang
sources:
  - https://git.sr.ht/~smlavine/colat
tasks:
  - gcc: |
      cd colat
      make clean
      make CC=gcc
  - clang: |
      cd colat
      make clean
      make CC=clang
